# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pwabuilder-cloudapk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["**/env/production.env","**/env/preview.env"]'
        env:
          APPLICATIONINSIGHTSCONNECTIONSTRING: ${{secrets.APPLICATIONINSIGHTSCONNECTIONSTRING}}

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://pwabuilder.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_b9de96342f904734ace234555a9c3e19 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_6b60970f88494b55afbbceef47af104a }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b9de96342f904734ace234555a9c3e19 }}/pwabuildercloudapk-prod:staging
          file: ./Dockerfile
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://pwabuilder.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b9de96342f904734ace234555a9c3e19 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6b60970f88494b55afbbceef47af104a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b9de96342f904734ace234555a9c3e19 }}/pwabuildercloudapk-prod:staging
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pwabuilder-cloudapk'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_203f107a9283469089377b5355bde9ec }}
          images: 'pwabuilder.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b9de96342f904734ace234555a9c3e19 }}/pwabuildercloudapk-prod:staging'

